version: '3.9'
services:
  go:
    container_name: go
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    tty: true
    ports: 
      - 8084:8080
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./go
        target: /var/go/app
    networks:
      - pj_slack_bot_nw

  db:
    container_name: db
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    restart: always
    tty: true
    ports:
      - 15432:5432
    env_file:
      - ./.env
    volumes:
      - pj_slack_bot_vol:/var/lib/postgresql/data
    networks:
      - pj_slack_bot_nw

volumes:
  pj_slack_bot_vol:
    name: pj_slack_bot_vol

networks:
  pj_slack_bot_nw:
    external: true